import { Inter } from "next/font/google";
import "./globals.css";

import Main from "@/components/Main";
import { getServerSession } from "next-auth";
import { NextAuthConfig } from "@/configs/NextAuthConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dark Store",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(NextAuthConfig)
  console.log(session);
  return (
    <html lang="ru">
      <head><link rel="icon" href="https://www.svgrepo.com/show/327418/logo-xing.svg" sizes="any" /></head>
      <body className={`${inter.className} min-h-screen`}>
        <Main session={session}>
          {children}
        </Main>
      </body>
    </html >
  );
}
